config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "home#index"
  resources :users, only: [:show, :update, :edit]
  resources :events, only: [:show]
  resources :activities, only: [:show] do
    resources :activity_images, only: [:new, :create]
    resources :feedbacks, only: [:new, :create]
  end
  resources :activity_images, only: [:destroy]
  resources :feedbacks, only: [:destroy]
  resources :trip_routes, only: [:show, :update, :new, :create] do
    resources :trip_route_activities, only: [:new, :create, :destroy]
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :trip_route_activities, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :trivia, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :activity_images, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true

  geocoded_by :address
  after_validation :geocode

  has_attached_file :image, styles: {
    thumb: "35x35#",
    square: "200x200#",
    medium: "300x300#"
  }, default_url: "/default_avatar.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/activity_image.rb
class ActivityImage < ApplicationRecord
  belongs_to :activity
  belongs_to :user

  has_attached_file :image, styles: {
    thumb: "35x35#",
    square: "200x200#",
    medium: "300x300#"
  }, default_url: "/default_avatar.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_attached_file :image, styles: {
    thumb: "35x35#",
    square: "200x200#",
    medium: "300x300#"
  }, default_url: "/default_avatar.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  geocoded_by :address
  after_validation :geocode

  scope :by_date, -> { order(start_at: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :activity
  belongs_to :user

  validates :body, presence: true
  validates :activity, presence: true

  scope :first_four_by_date, -> { order(created_at: :desc).first(4) }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
  has_many :question_options, dependent: :destroy

  validates :body, presence: true
  validates :activity, presence: true
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validates :question, presence: true
end

app/models/quiestion_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validates :question, presence: true
end

app/models/trip_route.rb
class TripRoute < ApplicationRecord
  belongs_to :user
  has_many :trip_route_activities, dependent: :destroy

  validates :transport, presence: true
  validates :user, presence: true

  geocoded_by :address
  after_validation :geocode

  scope :by_date, -> { order(created_at: :desc) }
  scope :latest, -> { order(created_at: :desc).first }
end

app/models/trip_route_activity.rb
class TripRouteActivity < ApplicationRecord
  belongs_to :trip_route
  belongs_to :activity

  validates :trip_route, presence: true, uniqueness: { scope: :activity }

  scope :top_three, -> { order(created_at: :desc).last(3) }
end

app/models/trivium.rb
class Trivium < ApplicationRecord
  belongs_to :activity

  validates :body, presence: true
  validates :activity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trip_routes, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :activity_images, dependent: :destroy
  has_many :trip_route_activities, through: :trip_routes

  has_attached_file :avatar, styles: {
    thumb: "35x35#",
    square: "200x200#",
    medium: "300x300#"
  }, default_url: "/default_avatar.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  after_filter "save_my_previous_url", only: [:new, :show, :create, :update]

  def show
    @activity = Activity.find params[:id]
    @trivium = @activity.trivia
    @questions = @activity.questions.order("RANDOM()").first(3)
    @images = @activity.activity_images.paginate(:page => params[:page], :per_page => 6)
    @activity_image = ActivityImage.new
    @feedbacks = @activity.feedbacks.first_four_by_date
    @feedback = Feedback.new
    @back_url = session[:my_previous_url]
  end

  private

  def save_my_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find params[:id]
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.name.capitalize
    end
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    @activity = Activity.find params[:activity_id]
    @feedback = @activity.feedbacks.new feedback_params

    if @feedback.save
      flash[:success] = "Success"
    else
      flash[:error] = @feedback.errors.full_messages.to_sentence
    end

    redirect_to :back
  end

  def destroy
    @feedback = Feedback.find params[:id]
    @feedback.destroy
    redirect_to :back
  end

  private

  def feedback_params
    params.require(:feedback).permit(:body).merge(user: current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/controllers/trip_routes_controller.rb
class TripRoutesController < ApplicationController
  def show
    @trip_route = TripRoute.find params[:id]
    @trip_route_activity = TripRouteActivity.new
    @trip_route_activities = @trip_route.trip_route_activities
    @hash = Gmaps4rails.build_markers(@trip_route_activities) do |trip_route, marker|
      marker.lat trip_route.activity.latitude
      marker.lng trip_route.activity.longitude
      marker.infowindow trip_route.activity.title.capitalize
    end

    if @trip_route.address.present?
      @activities = Activity.near([@trip_route.latitude, @trip_route.longitude], @trip_route.transport, units: :km)
    else
      @activities = Activity.all
    end
  end

  def new
    @trip_route = TripRoute.new
    @activities = Activity.all
  end

  def create
    @trip_route = TripRoute.new trip_route_params

    if @trip_route.save
      flash[:success] = "Success"
      redirect_to @trip_route

    else
      flash[:error] = @trip_route.errors.full_messages.to_sentence
      redirect_to :back
    end

  end

  def update
    @trip_route = TripRoute.find params[:id]
    @trip_route.update trip_route_params
    redirect_to @trip_route
  end

  private

  def trip_route_params
    params.require(:trip_route).permit(:transport, :trip_route_activities, :active, :address).merge(user: current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user, only: [:show, :update, :edit]

  def show
    @trip_route = TripRoute.new
    @trip_routes = @user.trip_routes.by_date.paginate(:page => params[:page], :per_page => 20)
    @images = @user.activity_images.paginate(:page => params[:page], :per_page => 8)
    @latest_trip_route = @user.trip_routes.latest

    if @latest_trip_route.present?
      @activities = @latest_trip_route.trip_route_activities.top_three
    end

    @events = Event.by_date.paginate(:page => params[:page], :per_page => 3)
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to @user
      flash[:success] = t ".success"
    else
      render :back
    end
  end

  private

  def user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:first_name, :surname, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/activities/_album.html.erb
<h2 class="col-xs-12">
  <%= t ".gallery_title" %>
</h2>

<section class="col-xs-12 row center-xs">
  <% @images.each do |image| %>
    <section class="col-xs-6 col-sm-4 col-md-3 col-lg-2 activity-image-wrapper row start-xs">
      <%= link_to image.image.url, class: "fancybox", rel: "activity-images" do %>
        <%= image_tag image.image(:square) %>
      <% end %>

      <span class="xs-side-pad">
        <% if image.user.first_name.present? or image.user.surname.present? %>
          <%= image.user.first_name %>
          <%= image.user.surname %>

        <% else %>
          <%= t (".anonymous") %>
        <% end %>
      </span>

      <span class="xs-side-pad">
        <%= image.created_at.strftime("%F") %>
      </span>

      <% if image.user == current_user %>
        <span class="xs-side-pad">
          <%= link_to "remove", activity_image_path(image), method: :delete %>
        </span>
      <% end %>
    </section>
  <% end %>
</section>
<%= will_paginate @images %>

<section class="col-xs-12 row center-xs">
  <h2 class="col-xs-12">
    <%= t ".upload_image_title" %>
  </h2>

  <section class="col-xs-12">
    <%= simple_form_for [@activity, @activity_image] do |f| %>
      <%= f.input :image %>
      <%= button_tag(type: 'submit', class: "btn btn-success md-top-margin") do %>
        <%= fa_icon "cloud-upload", text: "Upload image" %>
      <% end %>
    <% end %>
  </section>
</section>

app/views/activities/_feedback.html.erb
<h2 class="col-xs-12">
  <%= t ".review_title" %>
</h2>

<section class="col-xs-12 row center-xs">
  <% @feedbacks.each do |feedback| %>
    <section class="col-xs-12">
      <p>
        <% if feedback.user == current_user %>
          <%= link_to feedback_path(feedback), class: "red", method: :delete do %>
            <%= fa_icon "times" %>
          <% end %>
        <% end %>

        <span class="italic">
          <%= feedback.body %>
        </span>
        -
        <% if feedback.user.first_name.present? or feedback.user.surname.present? %>
          <%= feedback.user.first_name %>
          <%= feedback.user.surname %>

        <% else %>
          <%= t ".anonymous" %>
        <% end %>
      </p>
    </section>
  <% end %>
</section>

<section class="col-xs-12">
  <%= simple_form_for [@activity, @feedback] do |f| %>
    <%= f.input :body, label: false, placeholder: (t ".placeholder"), input_html: {rows: 5} %>
    <%= button_tag(type: 'submit', class: "btn btn-success md-top-margin") do %>
      <%= fa_icon "pencil-square-o", text: "Write feedback" %>
    <% end %>
  <% end %>
</section>

app/views/activities/_quiz.html.erb
<h2 class="col-xs-12">
  <%= t ".question_title" %>
</h2>

<% @questions.each do |question| %>
  <section class="col-xs-12 col-md-6 md-top-margin">
    <%= question.body %>
  </section>

  <section class="col-xs-12 row center-xs">
    <% question.question_options.each do |question_option| %>
      <% if question_option.right_answer? %>
        <span class="btn btn-yellow col-xs-12 col-sm-8 col-md-6 question-option ro">
          <%= question_option.body %>
        </span>

      <% else %>
        <span class="btn btn-yellow col-xs-12 col-sm-8 col-md-6 question-option">
          <%= question_option.body %>
        </span>
      <% end %>
    <% end %>
  </section>
<% end %>

<span class="btn btn-success submit-quiz md-top-margin">
  <%= (fa_icon "eye", text: t(".show_answer_text")) %>
</span>

app/views/activities/_trivium.html.erb
<h2><%= t ".fun_title" %></h2>

<% @trivium.each do |trivia| %>
  <section class="col-xs-12">
    <%= trivia.body %>
  </section>
<% end %>

app/views/activities/show.html.erb
<section style="background-image:
  linear-gradient(
  rgba(0, 0, 0, 0.3),
  rgba(0, 0, 0, 0.3)
  ),
  url('<%= @activity.image %>');", class="activity-wallpaper row center-xs middle-xs">

  <section class="col-xs-12 col-md-8">
    <h2>
      <%= @activity.title %>
    </h2>

    <%= @activity.description %>
  </section>
</section>

<section class="container container-overflow">
  <section class="row between-md">

    <section class="col-xs-12 col-md-8 no-padding-md">
      <section class="col-xs-12 whiteframe row center-xs">

        <span class="col-xs-12 row star-xs">
          <%= link_to @back_url, class: "btn btn-success col-xs-3" do %>
            <%= fa_icon "arrow-left" %>
            <%= t ".back_btn" %>
          <% end %>
        </span>

        <span class="col-xs-12">
          <%= render "trivium" %>
        </span>
      </section>

      <section class="col-xs-12 whiteframe row center-xs md-top-margin">
        <%= render "quiz" %>
      </section>

      <section class="col-xs-12 whiteframe row center-xs md-top-margin">
        <%= render "album" %>
      </section>
    </section>

    <section class="col-xs-12 col-md md-left-margin-gt-lg no-padding-md">
      <section class="col-xs-12 whiteframe row center-xs">
        <%= render "feedback" %>
      </section>
    </section>
  </section>
</section>

app/views/trip_routes/_active.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyCqtDEcW-KAkp5E7_DADBNOimpgEDZz1p4"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<h2 class="center-xs no-margin md-top-margin">
  <%= t ".active_activities" %>
</h2>

<section class="row center-xs">

  <% @trip_route_activities.each do |trip_route_activity| %>
    <section class="col-xs-12 col-sm-8 col-md-4 activity-wrapper activity-active">
      <section class="activity-header row middle-xs">
        <section style="background-image:
          linear-gradient(
          rgba(0, 0, 0, 0.3),
          rgba(0, 0, 0, 0.3)
          ),
          url('<%= trip_route_activity.activity.image %>');", class="col-xs-9 activity">

          <span class="activity-title">
            <%= truncate (trip_route_activity.activity.title), length: 15 %>
          </span>
        </section>

        <%= link_to (fa_icon "map-marker", text: "I'm here"), trip_route_activity.activity, class: "lighten xs-left-margin uppercase col-xs" %>
      </section>
    </section>
  <% end %>
</section>

<div class="map-div">
  <div id="directions" class="gmap"></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      zoom: 9,
      center: {lat: 60.4876438, lng: 15.4260946}

    },
    internal: {
      id: 'directions'
    }
  },

  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);;
    handler.bounds.extendWith(markers);
  }
);
</script>

app/views/trip_routes/_form.html.erb
<%= simple_form_for trip_route do |f| %>
  <section class="col-xs-12">
    <%= t ".current_position_title" %>
  </section>

  <section class="col-xs-12 center-xs">
    <%= f.input :address, label: false %>
  </section>

  <section class="col-xs-12 center-xs">
    <%= "What is your transport?" %>
  </section>

  <section class="col-xs-12 center-xs">
    <%= f.input :transport, label: false, collection: [["Walk", 10], ["Bike", 20], ["Car", 40]] %>
  </section>

  <section class="col-xs-12 center-xs">
    <%= button_tag(type: 'submit', class: "btn btn-success md-top-margin") do %>
      <%= fa_icon "plus", text: "Create route" %>
    <% end %>
  </section>
<% end %>

app/views/trip_routes/_inactive.html.erb
<section class="container">
  <section class="col-xs-12 center-xs">
    <h2><%= t ".select_activities" %></h2>
  </section>

  <section class="row">
    <section class="col-xs-12 row activities-wrapper center-xs">
      <% @activities.each_with_index do |activity, index| %>

        <section class="col-xs-12 col-sm-8 col-md-4 activity-wrapper">
          <section class="activity-header row middle-xs">
            <section style="background-image:
              linear-gradient(
              rgba(0, 0, 0, 0.3),
              rgba(0, 0, 0, 0.3)
              ),
              url('<%= activity.image %>');", class="activity">

              <span class="activity-title">
                <%= truncate (activity.title), length: 15 %>
              </span>
            </section>

            <%= fa_icon "angle-right", class: "col-xs activity-arrow" %>
          </section>

          <section class="activity-content">
            <section class="col-xs-12 center-xs">
              <h3>
                <%= truncate (activity.title), length: 25 %>
              </h3>
              <%= image_tag activity.image(:square) %>
            </section>

            <%= activity.description %>

            <%= simple_form_for [@trip_route, @trip_route_activity] do |f| %>
              <%= f.hidden_field :activity_id, value: activity.id %>
              <%= f.button :submit, class: "btn btn-success md-margin" %>
            <% end %>
          </section>
        </section>
      <% end %>
    </section>
  </section>

  <section class="col-xs-12 center-xs">
    <h2><%= t ".selected_activities" %></h2>
    <section class="col-xs-12 row activities-wrapper center-xs">
      <% @trip_route_activities.each do |trip_route_activity| %>

        <section class="col-xs-12 col-sm-8 col-md-4 activity-wrapper">
          <section class="activity-header row middle-xs">
            <section style="background-image:
              linear-gradient(
              rgba(0, 0, 0, 0.3),
              rgba(0, 0, 0, 0.3)
              ),
              url('<%= trip_route_activity.activity.image %>');", class="activity">

              <span class="activity-title">
                <%= truncate (trip_route_activity.activity.title), length: 15 %>
              </span>
            </section>

            <%= link_to (fa_icon "times"), trip_route_trip_route_activity_path(@trip_route, trip_route_activity), method: :delete, class: "activity-times col-xs" %>
          </section>
        </section>
      <% end %>
    </section>
  </section>

  <section class="row center-xs md-margin">
    <%= simple_form_for @trip_route do |f| %>
      <%= f.hidden_field :active, value: true %>
      <%= button_tag(type: 'submit', class: "btn btn-success md-top-margin") do %>
        <%= fa_icon "play", text: "Start trip" %>
      <% end %>
    <% end %>
  </section>
</section>

app/views/trip_routes/new.html.erb
<h2>Skapa en ny trip!</h2>

<% @activities.each do |activity| %>
  <%= activity.title %>
<% end %>

<%= render "form", trip_route: @trip_route %>

app/views/trip_routes/show.html.erb
<% if @trip_route.active? %>
  <%= render "active" %>

<% else %>
  <%= render "inactive" %>
<% end %>

app/views/users/_activities.html.erb
<h2 class="col-xs-12">
  Latest activities
</h2>

<% if @activities.present? %>
  <% @activities.each do |activity| %>
    <section class="col-xs-12 col-sm-8 col-md-12 row middle-xs activity-box">
      <%= image_tag activity.activity.image(:square), class: "activity-sm" %>

      <%= link_to activity.activity do %>
        <span class="activity-box-title darken">
          <%= truncate (activity.activity.title), length: 15 %>
        </span>
      <% end %>
    </section>
  <% end %>
<% end %>

app/views/users/_events.html.erb
<h2>
  Upcoming events in Dalarna
</h2>

<% @events.first(3).each do |event| %>
  <section class="row col-xs-12 md-top-margin center-xs pointer">
    <%= link_to event_path(event.id) do %>
      <section class="col-xs-12 col-lg-4">
        <%= image_tag event.image(:square) %>
      </section>

      <section class="col-xs-12 col-md-8">
        <h3 class="no-margin lg-top-margin darken">
          <%= event.name %>
        </h3>
        <span class="italic no-pad muted">
          <%= l(event.start_at, format: "%A %d %B, %H:%M") %>
        </span>
        <section class="col-xs-12 md-top-margin start-xs darken">
          <%= event.description.truncate(200) %>
        </section>
      <% end %>
    </section>

  </section>
<% end %>
<%= will_paginate @events %>

app/views/users/_header.html.erb
<section class="col-xs-12 col-md-6">
  <%= image_tag @user.avatar(:square), class: "user-wallpaper-avatar" %>

  <h3 class="col-xs">
    <%= @user.first_name %>
    <%= @user.surname %>
  </h3>

  <% if @user == current_user %>
    <section class="col-xs-12">
      <%= link_to edit_user_path, class: "col-xs-12 btn btn-success" do %>
        <%= fa_icon "cog", text: "Edit profile" %>
      <% end %>
    </section>
  <% end %>
</section>

<section class="col-xs-12 col-md row center-xs end-md">
  <h3>
    <%= t ".create_new_route_title" %>
  </h3>

  <section class="col-xs-12 row center-xs end-md">
    <%= render "trip_routes/form", trip_route: @trip_route %>
  </section>
</section>

app/views/users/_images.html.erb
<h2 class="col-xs-12 md-margin">
  Imagegallery
</h2>

<section class="col-xs-12 row center-xs">
  <% @images.each do |image| %>
    <section class="col-xs-6 col-sm-4 col-md-3 activity-image-wrapper row start-xs">
      <%= link_to image.image.url, class: "fancybox", rel: "activity-images" do %>
        <%= image_tag image.image(:square) %>
      <% end %>

      <%= link_to "remove", activity_image_path(image), method: :delete, class: "hideable-link hideable-link-active" %>
    </section>
  <% end %>
</section>

<section class="col-xs-12 md-top-margin">
  <%= will_paginate @images %>
</section>

<section class="col-xs-4 md-top-margin">
  <span class="btn md-margin visible-btn">
    Edit
  </span>

  <span class="btn md-margin done-btn done-btn-inactive">
    Done
  </span>
</section>

app/views/users/_routes.html.erb
<h2 class="col-xs-12">
  Your Routes
</h2>

<% @trip_routes.each do |trip_route| %>
  <section class="col-xs-12">
    <%= link_to trip_route.created_at.strftime("%d %B %Y"), trip_route %>

    <% if trip_route.transport == 10 %>
      <%= fa_icon "street-view" %>
    <% elsif trip_route.transport == 20 %>
      <%= fa_icon "bicycle" %>
    <% else %>
      <%= fa_icon "car" %>
    <% end %>

    <% if trip_route.active? %>
      <%= fa_icon "check", class: "success" %>
    <% else %>
      <%= fa_icon "times", class: "error" %>
    <% end %>
  </section>
<% end %>
<%= will_paginate @trip_routes %>

app/views/users/edit.html.erb
<section class="container">
  <section class="row center-xs md-margin">
    <section class="col-xs-12 col-md-6 whiteframe">
      <h2>
        Edit User
      </h2>

      <section class="row center-xs">
        <%= simple_form_for @user do |f| %>
          <section class="col-xs-12">
            <%= f.input :first_name, label: false, placeholder: "First name" %>
          </section>

          <section class="col-xs-12">
            <%= f.input :surname, label: false, placeholder: "Surname" %>
          </section>

          <section class="col-xs-12 md-top-margin">
            <%= f.input :avatar %>
          </section>

          <section class="col-xs-12 md-top-margin">
            <%= button_tag(type: 'submit', class: "btn btn-success md-top-margin") do %>
              <%= fa_icon "wrench", text: "Update your profile" %>
            <% end %>
          </section>
        <% end %>
      </section>
    </section>
  </section>
</section>

app/views/users/show.html.erb
<section class="user-wallpaper center-xs">
</section>

<section class="container">
  <section class="row between-md">

    <section class="col-xs-12 col-md-8 no-padding-md">
      <section class="col-xs-12 row whiteframe center-xs start-md">
        <%= render "header" %>
      </section>

      <section class="col-xs-12 row center-xs whiteframe md-top-margin">
        <%= render "images" %>
      </section>

      <section class="col-xs-12 row center-xs whiteframe md-top-margin">
        <%= render "events" %>
      </section>
    </section>

    <section class="col-xs-12 col-md md-left-margin-gt-lg no-padding-md">
      <section class="col-xs-12 row center-xs middle-xs no-padding">
        <%= render "activities" %>
      </section>

      <section class="col-xs-12 row center-xs whiteframe">
        <%= render "routes" %>
      </section>
    </section>
  </section>
</section>